FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git protobuf-dev protobuf

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

ENV PATH="${PATH}:$(go env GOPATH)/bin"

RUN protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    api/proto/job.proto

RUN CGO_ENABLED=0 GOOS=linux go build -o manager ./cmd/manager

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /build/manager .

EXPOSE 8080 50051

CMD ["./manager"]
